export const ProjectImages = {
    logo: 'assets/images/logo.png',
    menu: 'assets/images/menu.png',
    rice: 'assets/images/rice.png',
    dahi: 'assets/images/dahi.png',
    roti: 'assets/images/roti.png',
    soup: 'assets/images/soup.png',
    cake: 'assets/images/cake.png',
    eggs: 'assets/images/eggs.png',
    pizza: 'assets/images/pizza.png',
    momos: 'assets/images/momos.png',
    pasta: 'assets/images/pasta.png',
    salad: 'assets/images/salad.png',
    tikka: 'assets/images/tikka.png',
    water: 'assets/images/water.png',
    thali: 'assets/images/thali.png',
    order: 'assets/images/order.png',
    wraps: 'assets/images/wraps.png',
    share: 'assets/images/share.png',
    sweets: 'assets/images/laddu.png',
    burger: 'assets/images/burger.png',
    cheese: 'assets/images/cheese.png',
    coffee: 'assets/images/coffee.png',
    hotDog: 'assets/images/hotdog.png',
    indian: 'assets/images/indian.png',
    google: 'assets/images/google.png',
    gallery: 'assets/images/gallery.png',
    chinese: 'assets/images/chinese.png',
    cookies: 'assets/images/cookies.png',
    noodles: 'assets/images/noodles.png',
    shakes: 'assets/images/smoothie.png',
    special: 'assets/images/special.png',
    namkeen: 'assets/images/namkeen.png',
    harshtag: 'assets/images/harshtag.png',
    iceCream: 'assets/images/iceCream.png',
    mocktail: 'assets/images/mocktail.png',
    sandwich: 'assets/images/sandwich.png',
    whatsapp: 'assets/images/whatsapp.png',
    location: 'assets/images/location.png',
    instagram: 'assets/images/instagram.png',
    mainCourse: 'assets/images/mainCourse.png',
    frenchFries: 'assets/images/frenchFries.png',
};

export const MenuData = {
    items: [
        { image: ProjectImages.rice, name: "Rice" },
        { image: ProjectImages.roti, name: "Roti" },
        { image: ProjectImages.dahi, name: "Dahi" },
        { image: ProjectImages.soup, name: "Soup" },
        { image: ProjectImages.pizza, name: "Pizza" },
        { image: ProjectImages.momos, name: "Momos" },
        { image: ProjectImages.pasta, name: "Pasta" },
        { image: ProjectImages.salad, name: "Salad" },
        { image: ProjectImages.tikka, name: "Tikka" },
        { image: ProjectImages.water, name: "Water" },
        { image: ProjectImages.wraps, name: "Wraps" },
        { image: ProjectImages.cake, name: "Dessert" },
        { image: ProjectImages.coffee, name: "Coffee" },
        { image: ProjectImages.shakes, name: "Shakes" },
        { image: ProjectImages.hotDog, name: "Hotdog" },
        { image: ProjectImages.cheese, name: "Paneer" },
        { image: ProjectImages.indian, name: "Indian" },
        { image: ProjectImages.sweets, name: "Sweets" },
        { image: ProjectImages.burger, name: "Burgers" },
        { image: ProjectImages.chinese, name: "Chinese" },
        { image: ProjectImages.noodles, name: "Noodles" },
        { image: ProjectImages.namkeen, name: "Namkeen" },
        { image: ProjectImages.sandwich, name: "Sandwich" },
        { image: ProjectImages.frenchFries, name: "Fries" },
        { image: ProjectImages.iceCream, name: "Ice Cream" },
        { image: ProjectImages.frenchFries, name: "Snacks" },
        { image: ProjectImages.mocktail, name: "Mocktails" },
        { image: ProjectImages.mocktail, name: "Beverages" },
        { image: ProjectImages.eggs, name: "Eggs/Omelette" },
        { image: ProjectImages.rice, name: "Rice & Biryani" },
        { image: ProjectImages.coffee, name: "Tea & Coffee" },
        { image: ProjectImages.roti, name: "Roti & Parantha" },
        { image: ProjectImages.mainCourse, name: "Main Course" },
    ]
};

export function getImageForCategory(categoryType) {
    const menuItem = MenuData.items.find(
        item => item.name.toLowerCase() === categoryType.toLowerCase()
    );
    if (!menuItem) return '';
    return menuItem.image;
}
